# Generated by Django 4.2.7 on 2023-11-30 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(5)])),
                ('Name', models.CharField(max_length=255)),
                ('No_of_guests', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('BookingDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(5)])),
                ('Title', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Inventory', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
